sudo: true
dist: trusty
language: node_js
node_js:
  - 12
install:
  - npm install -g markdownlint-cli
stages:
  - lint
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: lint
      script:
      - markdownlint content
    - stage: deploy
      script:
      - git submodule update --init --recursive
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - ls -ltr ./themes/docdock
      - docker build -t commonplace .
      - docker images
      - docker tag commonplace $DOCKER_USERNAME/commonplace
      - docker push $DOCKER_USERNAME/commonplace
