arch: 
- amd64
- arm64
os: linux

sudo: true
dist: bionic

jobs:
  include:
    - stage: build docker image
      script:
      - git submodule update --init --recursive
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - ls -ltr ./themes/docdock
      - docker build -t commonplace .
      - docker images
      - docker tag commonplace $DOCKER_USERNAME/commonplace
      - docker push $DOCKER_USERNAME/commonplace
